remote_theme: daviddarnes/garth
include: README.md
title: Omega Earth Art
collections:
  posts:
    title: Welcome!
    output: true
    description: "My name is Sam, and I'm making fantasy (and maybe occasionally other) drawrings"
    ## Enjoy my [art](art.md)! **OR** Read my [comics!](comics.md)
    ### You can buy original art on my [Etsy](https://www.etsy.com/shop/OmegaEarthArt)
    #### Or even follow me on [Instagram](https://www.instagram.com/omegaearthart/) OR [Twitter](https://twitter.com/OmegaEarthArt)
